add_newline = false

[character]
success_symbol = "[â–¶](bold red)[â–¶](bold yellow)[â–¶](bold cyan)"

[directory]
truncation_length = 1
truncate_to_repo = true
style = "fg:#8ec07c"

[aws]
format = '\[[$symbol($profile)]($style)\]'
style = "fg:#fe8019"
symbol = "ï”¬ "

[docker_context]
symbol = "ïŒˆ "

[git_branch]
format = '\[[$symbol$branch]($style)\]'
style = "fg:#fabd2f"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
style = "fg:#fb4934"

[golang]
format = '\[[$symbol($version)]($style)\]'
style = "fg:#83a598"
symbol = "î˜§ "

[gradle]
format = '\[[$symbol($version)]($style)\]'
version_format = "v${raw}"
symbol = 'ðŸ…¶'
detect_folders = ["gradle"]
style = "bold bright-cyan"

[java]
format = '\[[${symbol}(${version})]($style)\]'

[kotlin]
format = '\[[$symbol($version)]($style)\]'

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
symbol = "î˜† "

[rust]
format = '\[[$symbol($version)]($style)\]'
symbol = "îž¨ "

[terraform]
format = '\[[$symbol$workspace]($style)\]'
detect_files = [".terraform-version"]
